login:
  pattern:  /login
  defaults: { _controller: DoctrineUserBundle:Auth:login }

loginSuccess:
  pattern:  /login/success
  defaults: { _controller: DoctrineUserBundle:Auth:success }

logout:
  pattern:  /logout
  defaults: { _controller: DoctrineUserBundle:Auth:logout }