doctrine_user_session_new:
    pattern:        /session/new
    defaults:       { _controller: DoctrineUserBundle:Session:new }
    requirements:   { _method: "GET" }

doctrine_user_session_create:
    pattern:        /session/new
    defaults:       { _controller: DoctrineUserBundle:Session:create }
    requirements:   { _method: "POST" }
