doctrine_user_user_new:
    pattern:        /user/new
    defaults:       { _controller: DoctrineUserBundle:User:new }
    requirements:   { _method: "GET" }

doctrine_user_user_create:
    pattern:        /user/new
    defaults:       { _controller: DoctrineUserBundle:User:create }
    requirements:   { _method: "POST" }

doctrine_user_user_delete:
    pattern:        /user/delete
    defaults:       { _controller: DoctrineUserBundle:User:delete }
    requirements:   { _method: "GET" }

doctrine_user_user_list:
    pattern:        /user/list
    defaults:       { _controller: DoctrineUserBundle:User:list }
    requirements:   { _method: "GET" }
